proxies:
- cipher: aes-256-gcm
  name: JMS-924690@c53s1.portablesubmarines.com:6876
  password: cMLV3ySg8rPUDksP
  port: 6876
  server: 104.194.73.87
  type: ss
- cipher: aes-256-gcm
  name: JMS-924690@c53s2.portablesubmarines.com:6876
  password: cMLV3ySg8rPUDksP
  port: 6876
  server: 93.179.113.228
  type: ss
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s3.portablesubmarines.com:6876
  network: tcp
  port: 6876
  server: 93.179.100.198
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s4.portablesubmarines.com:6876
  network: tcp
  port: 6876
  server: 212.50.247.168
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s5.portablesubmarines.com:6876
  network: tcp
  port: 6876
  server: 104.245.102.153
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s801.portablesubmarines.com:6876
  network: tcp
  port: 6876
  server: 23.83.236.238
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
proxy-groups:
- interval: 300
  name: auto
  proxies:
  - JMS-924690@c53s1.portablesubmarines.com:6876
  - JMS-924690@c53s2.portablesubmarines.com:6876
  - JMS-924690@c53s3.portablesubmarines.com:6876
  - JMS-924690@c53s4.portablesubmarines.com:6876
  - JMS-924690@c53s5.portablesubmarines.com:6876
  - JMS-924690@c53s801.portablesubmarines.com:6876
  type: url-test
  url: http://www.gstatic.com/generate_204
