proxies:
- cipher: aes-256-gcm
  name: JMS-924690@c53s1.portablesubmarines.com:6876
  password: cMLV3ySg8rPUDksP
  port: 6876
  server: 172.96.255.2
  type: ss
- cipher: aes-256-gcm
  name: JMS-924690@c53s2.portablesubmarines.com:6876
  password: cMLV3ySg8rPUDksP
  port: 6876
  server: 172.96.254.32
  type: ss
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s3.portablesubmarines.com:6876
  network: tcp
  port: 6876
  server: 93.179.101.2
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s4.portablesubmarines.com:6876
  network: tcp
  port: 6876
  server: 212.50.249.20
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s5.portablesubmarines.com:6876
  network: tcp
  port: 6876
  server: 162.248.76.36
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s801.portablesubmarines.com:6876
  network: tcp
  port: 6876
  server: 23.83.238.103
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
proxy-groups:
- interval: 300
  name: auto
  proxies:
  - JMS-924690@c53s1.portablesubmarines.com:6876
  - JMS-924690@c53s2.portablesubmarines.com:6876
  - JMS-924690@c53s3.portablesubmarines.com:6876
  - JMS-924690@c53s4.portablesubmarines.com:6876
  - JMS-924690@c53s5.portablesubmarines.com:6876
  - JMS-924690@c53s801.portablesubmarines.com:6876
  type: url-test
  url: http://www.gstatic.com/generate_204
