proxies:
- cipher: aes-256-gcm
  name: JMS-924690@c53s1.portablesubmarines.com:7713
  password: cMLV3ySg8rPUDksP
  port: 7713
  server: 93.179.114.183
  type: ss
- cipher: aes-256-gcm
  name: JMS-924690@c53s2.portablesubmarines.com:7713
  password: cMLV3ySg8rPUDksP
  port: 7713
  server: 97.64.25.70
  type: ss
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s3.portablesubmarines.com:7713
  network: tcp
  port: 7713
  server: 198.181.59.169
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s4.portablesubmarines.com:7713
  network: tcp
  port: 7713
  server: 212.50.249.29
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s5.portablesubmarines.com:7713
  network: tcp
  port: 7713
  server: 104.245.100.33
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
- alterId: 0
  cipher: auto
  name: JMS-924690@c53s801.portablesubmarines.com:7713
  network: tcp
  port: 7713
  server: 23.83.233.144
  tls: false
  type: vmess
  uuid: 005b8be6-7cc3-4b45-8a91-7cb3d8da0486
  ws-headers: {}
  ws-path: ''
proxy-groups:
- interval: 300
  name: auto
  proxies:
  - JMS-924690@c53s1.portablesubmarines.com:7713
  - JMS-924690@c53s2.portablesubmarines.com:7713
  - JMS-924690@c53s3.portablesubmarines.com:7713
  - JMS-924690@c53s4.portablesubmarines.com:7713
  - JMS-924690@c53s5.portablesubmarines.com:7713
  - JMS-924690@c53s801.portablesubmarines.com:7713
  type: url-test
  url: http://www.gstatic.com/generate_204
