name: Jekyll Build and Deploy

on:
  push:
    branches:
      - content # 监听 content 分支的 push 事件
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: 'content' # 检出 content 分支

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: head # 使用最新稳定版本的Ruby

    - name: Install Bundler
      run: gem install bundler

    - name: Install Dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: Build Site with Jekyll
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master # 将构建产物推送到 master 分支
        publish_dir: ./_site # Jekyll构建的输出目录
