name: Build and Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: head

    - name: Install Bundler
      run: gem install bundler

    - name: Install Dependencies
      run: bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master # The branch the site will deploy to
        publish_dir: ./_site # The directory the action should deploy
        force_orphan: true # Forcefully re-creates the deployment branch. Useful to keep a clean commit history in the deployment branch.
