name: GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
  
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v4
        with:
          title: Compressed Images Nightly
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}

      - name: Checkout Theme Submodules
        if: github.ref == 'refs/heads/master'  # Only checkout submodules when pushing to master
        run: |
          git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Replace Image Paths in Markdown
        run: |
          find content -type f -name "*.md" | xargs sed -i 's#(\.\./assets/images/\(Y[0-9]*Q[0-9]*\)/\([^)]*\.\(jpg\|jpeg\|png\|gif\)\))#(https://raw.githubusercontent.com/lxulxu/lxulxu/lxulxu.github.io/master/assets/images/Y2022Q2/\1/\2?raw=true)#g'
          git add content/**/*.md
          git commit -m "Update image paths in Markdown" || echo "No changes to commit"
          git push origin master


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public