name: Update Image Links in Markdown Files

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment

    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Replace Image Paths in Markdown
        run: |
          find content -name '*.md' | while read file; do
            sed -i 's/\(\!\[.*\]\)(\.\.\/assets\/images\/\(Y[0-9]*Q[0-9]*\)\/\(.*\))/\1(https:\/\/raw.githubusercontent.com\/lxulxu\/lxulxu.github.io\/master\/assets\/images\/\2\/\3?raw=true)/g' "$file"
          done
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git add .
          git commit -m "Update Image Links in Markdown Files" -a || echo "No changes to commit"
          git push